### ISSUE TITLE
add POP and PLHIV API

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#20]
- function to pull POP_EST and PLHIV from DATIM
- user to define level - OU/SNU1/PSNU

relates to this [ticket in COVIDutilities](https://github.com/USAID-OHA-SI/COVIDutilities/issues/6)

**Comment by baboyma** [comment]
Should we duplicate `Wavelength::get_datim_targets` in `glamr` (Need to avoid requiring another in house package here)

@achafetz

**Comment by achafetz** [comment]
100% agree

**Comment by baboyma** [comment]
Great. I will create another issue and push it through there.

**Comment by baboyma** [comment]
I will leverage function under #40

**Comment by baboyma** [comment]
Note: this will be under: `datim_pops()`

**Comment by baboyma** [comment]
Completed. Need help testing this.
