### ISSUE TITLE
Update identifypd to use filename

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#21]
Function to identify period from filename using date in PEPFAR calendar

**Comment by baboyma** [comment]
return_latest(si_path(), "OU_IM") %>% identify_pd()

This is resolved

**Comment by achafetz** [comment]
this was resolved with [`source_info()`](https://usaid-oha-si.github.io/glamr/reference/source_info.html). Not sure why I didn't close it. I think we should drop `identify_pd()` because its too similar in name to `gophr::identifypd()` which is extracting the period from the loaded MSD data frame.
