### ISSUE TITLE
Incoporate get_*() from gisr()

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#24]
Updates from `gisr()` from @baboyma

**Comment by baboyma** [comment]
All these are moving here: 

`https://github.com/USAID-OHA-SI/gisr/blob/884bcd491ba9d50d43dbd3eba3448ef5fd4feb61/R/utilities.R#L1-L387`

**Comment by baboyma** [comment]
I will load them in `get_outable()`

**Comment by baboyma** [comment]
All functions have been moved.
