### ISSUE TITLE
Add get_email() 

### ISSUE THREAD

**Issue by baboyma** [USAID-OHA-SI/glamr#31]
get_email()  should work with set_email() and load_secret()

**Comment by achafetz** [comment]
I would propose instead we update how we store our email in `options` so we can take advantage of just using `drive_auth()` without having to specify email.

`options(gargle_oauth_email = "jenny@example.com")`

which is then called in the same way in `drive_auth()` and `gs4_auth()`
```
drive_auth(
  email = gargle::gargle_oauth_email(),
  path = NULL,
  scopes = "https://www.googleapis.com/auth/drive",
  cache = gargle::gargle_oauth_cache(),
  use_oob = gargle::gargle_oob_default(),
  token = NULL
)
```

--> @achafetz to update `set_email()` and `load_secrets`
