### ISSUE TITLE
Create new function to export local files for google drive

### ISSUE THREAD

**Issue by baboyma** [USAID-OHA-SI/glamr#41]
export_drivefile()

Requirement: 
- Opposite of `import_drivefile()`
- Add options to overrite existing file: default = T
- Add options to check / create directory

**Comment by baboyma** [comment]
I have a `export_drivefile` function ready and now wondering if it makes sense to add an optional `export_as`.
This will be tricky on a batch update. Thoughts?

**Comment by achafetz** [comment]
I think it makes sense to include. This will allow you to export as a Google Sheet or Google Doc, rather than xlsx, csv, or docx. It may complicate things if you are batching different types of files, but overall I think it will be beneficial

**Comment by baboyma** [comment]
This was resolved from #41
