### ISSUE TITLE
Wrapper function to grab pano data at different scales / geographies

### ISSUE THREAD

**Issue by tessam30** [USAID-OHA-SI/glamr#43]
- [ ] can we have a wrapper that would bundle the `pano_` functions into a single helper. Something like a function that you enter an OU (or list), a level (Site, PSNU, OU) and you get back a download or series of downloads?

**Comment by baboyma** [comment]
Hummm, Including archives?

**Comment by baboyma** [comment]
`pano_extract_msds()` added to address this need.
