### ISSUE TITLE
clean_column does not run with FSD

### ISSUE THREAD

**Issue by benjaminnk** [USAID-OHA-SI/glamr#44]
When I run clean_column on the financial datasets, it does not work as there is no psnu column. Can we add in a line for just the FSD to operate on "operatingunit" or "country" column?

**Comment by baboyma** [comment]
This function has a parameter `colname` set to "psnu" by default. You will need to change that to the column you want updated.

eg: `clean_column(.data = df_fsd, colname = "country")`

Let me know if the issue persist

**Comment by baboyma** [comment]
@benjaminnk Did the proposed solution worked? Let me know so I can close this issue.

**Comment by benjaminnk** [comment]
@baboyma yes that is working now thank you!
