### ISSUE TITLE
cannot get gdrive_metadata to work

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#48]
When I try using `gdrive_metadata()` I run into errors. 

```
usergroup_gs_id <- as_id("1XEN6w_pl5QoPSvyHCrCunIXtms_gVc-C")

ug_files <- drive_ls(usergroup_gs_id) 

ug_files %>% 
  slice_head(n = 1) %>% 
  gdrive_metadata()

ug_files %>% 
  slice_head(n = 1) %>% 
  gdrive_metadata(TRUE)
```

Running either of the two lines (with/without `show_details`), I get errors that the columns are missing.

![image](https://user-images.githubusercontent.com/8933069/139740491-86d4eb12-0435-41be-a01d-121dcf6e7767.png)

@baboyma do you know what is wrong here? Are the column names dynamic when pulled resulting in different columns return, is it from the [renaming of the columns](https://github.com/USAID-OHA-SI/glamr/blob/167b2da8d36c0a8c7b14a22717755e13e6af2ddb/R/import_drivefile.R#L92), or is the issue [resulting from `janitor::clean_names()`]( https://github.com/USAID-OHA-SI/glamr/blob/167b2da8d36c0a8c7b14a22717755e13e6af2ddb/R/import_drivefile.R#L97)

**Comment by baboyma** [comment]
Good catch - looks like google adds `original_name` variable only when there is a file that was renamed within the folder.
So i will make the column dynamic.

**Comment by baboyma** [comment]
This was fixed - Please give it a try when you can. @achafetz

**Comment by achafetz** [comment]
Re-ran with the updates and no minor differences in the errors, but errors nonetheless. And added an explicit reference to `str_remove()`.
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(googledrive)
library(glamr)

usergroup_gs_id <- as_id("1XEN6w_pl5QoPSvyHCrCunIXtms_gVc-C")

load_secrets("email")

ug_files <- drive_ls(usergroup_gs_id) 

ug_files %>% 
  slice_head(n = 1) %>% 
  gdrive_metadata()
#> Error in `dplyr::select()`:
#> ! Can't subset columns that don't exist.
#> x Column `size` doesn't exist.

ug_files %>% 
  slice_head(n = 1) %>% 
  gdrive_metadata(TRUE)
#> Error in `stop_subscript()`:
#> ! Can't subset columns that don't exist.
#> x Column `permissions` doesn't exist.
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by baboyma** [comment]
This is due to changing metadata structure - please continue to raise till google reaches a stable version.
