### ISSUE TITLE
Removing pagination

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#51]
I was only returned a partial list of indicators when I ran `datim_dim_items("Technical Area")`. 

To resolve this, [I added `?paging=false` to the url](https://github.com/USAID-OHA-SI/glamr/commit/e76d72a28edf978fe6515d63775e820f83b8cc88).

```
  # Update url
  url_dims <- glue::glue("{url}/{dim_id}/items?paging=false")
````

I think this is the only place that it's needed. I check the other [datim functions](https://github.com/USAID-OHA-SI/glamr/blob/main/R/extract_datim.R) and think everything else should be okay. @baboyma can you give it a once over and make sure that is the only place it was needed?

**Comment by baboyma** [comment]
Your url query should work. I may have introduced another bug. `?` needs to escaped: `\\?paging=true`
