### ISSUE TITLE
Want to remove WCF from USAID/WCF in FSD

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#52]
The FSD now breaks out the USAID working capital fund (WCF) in `fundingagency`, but want this lumped into USAID.

USAID -> USAID
USAID/WCF -> USAID

**Comment by achafetz** [comment]
Current function exists `clean_agency`, but removes prefix (eg HHS).

https://github.com/USAID-OHA-SI/glamr/blob/e210e3e364de9a3e3248f6c0db436066346a9de6/R/clean_columns.R#L131-L137

This actually breaks out State into it's desperate pieces, when we would want those lumped together.

**We want to update `clean_agency` to breakout HHS agencies, but lump all others.**

Data for testing with `clean_agency`

```
.data<- tibble::tribble(
  ~fundingagency,
           "DOD",
       "HHS/CDC",
      "HHS/HRSA",
    "HHS/SAMHSA",
            "PC",
         "State",
      "State/AF",
     "State/EAP",
     "State/EUR",
     "State/PRM",
    "State/SGAC",
     "State/WHA",
         "USAID",
     "USAID/WCF"
  ) 
```

May be useful to write as [unit test](https://r-pkgs.org/tests.html#test-structure) while developing :)

**Comment by benjaminnk** [comment]
Updated and fixed
