### ISSUE TITLE
Credential management

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#6]
Need to think through an improved way to store usernames/passwords to standardize so all of our code can be run without manually changing usernames or locations of where they're stored.

We use `keyringr` for DATIM password, but want a better way to store **usernames** so they are not in scripts. @baboyma and @tessam30 have local files for usernames that are sourced. These obviously sit in different locations on diff machines.

It may be optimal maybe switching to using a package like `keyring`. We could all then use a standard name for account - eg "DATIM" or "email" - in a wrapper around `keyring` to pull our username (for DATIM) or email (for `googledrive` or `googlesheets4`)

FYI @baboyma @tessam30 @jaliasd @gsarfaty

**Comment by achafetz** [comment]
`glamr` now use `keyringr` to save/access in your OS credential store. 

to setup, need to store USAID email for use with `googledrive` and `googlesheets4`
```
#store USAID email
set_email("rshah@usaid.gov")
```

and need to store DATIM credentials. You will provide your username in `set_datim()` and will be prompted to provide your password via the RStudio API.

```
#store USAID email
set_datim("rajshah")
```

You now have your credential stored locally for us going forward. To load during a session, you will just add `load_secrets()` at the beginning of your script. Your DATIM username will be stored and it will authenticate your Google Drive session for use with `googledrive` and `googlesheets4`

```
load_secrets()
user <- getOption("datim")
ou_table <- datim_outable(user, datim_pwd())
```

**Comment by achafetz** [comment]
@baboyma can we reuse Pickering code/logic to log into DATIM and cache the creds so we don't have to pass the credentials through every time? Do you see any issues with this?

https://github.com/jason-p-pickering/datim-validation/blob/f6020cfc6b9bcbf292c91ac7ec74a93f67f5cd39/R/loadSecrets.R#L34-L54

**Comment by baboyma** [comment]
We could but I wouldn't recommend it.

I think it's better, now that we have a working load_secrets(), to add glamr::datim_user() and glamr::datim_pwd() to some of the datim calls so one does not have to pass them to the function.

Alternatively, we could set username & password to NULL and let functions check (if not set) and then retrieve the values
