### ISSUE TITLE
Credential Management - Workbench storage

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/glamr#66]
Need to consider how we will need to adjust our credential management strategy when using RStudio/Posit Workbench. 

When local, continue using `keyring`. When in Workbench, need to figure out how to leverage IAM (Identity and Access Management)

**Comment by baboyma** [comment]
This will need to be part of Desktop and User specific Tasks (work around for lack of systems integration).

**Comment by achafetz** [comment]
To note, you can use keyring and password protect the file on Workbench
